
( Router Facing Operation - Inches )
( Tool: 2" Surfacing End Mill )
( Material: MDF Sheet 24" x 48" )
( Work Zero: Upper Right Corner of Material )
( Facing Depth: 0.020" - chosen for light finish pass )
( Step Over: 0.5" )
( Total Width to Face: 24.5" )
( Total Height to Face: 38.5" )
( Number of Passes: 38 )
( Feedrate: 100 IPM )
G20             ( Set units to inches )
F100.           ( Feedrate 100 inches per minute )
M3              ( Spindle on clockwise )
G00 X0. Y0.     ( Rapid to work zero )
G00 Z0.         ( Rapid to tool offset )

( Move to starting position )
G91 Z-0.020     ( Plunge to facing depth of -0.020" )
M97 P100 L38    ( Call subroutine at 0100 38 times for 38 inches))
G91 X-24.5      ( Move to X -24.5" absolute )
G91 Y-0.5       ( Increment Y by -0.5" to finish the last pass )
G91 X0.0        ( Move to X 0.0" absolute )
G90 Y0.0        ( Return to Y 0.0" absolute )
G90 Z0.2        ( Retract to safe height )
M5              ( Spindle stop )
M30             ( End of program )

( Subroutine to face across X and decrement Y )
O100            ( Subroutine label 100 )
G91 X-24.5      ( Move to X -24.5" absolute )
G91 Y-0.5       ( Increment Y by -0.5" to finish the last pass )
G91 X0.0        ( Move to X 0.0" absolute )
G91 Y0.5		( Complete pass loop on edge of material )
G91 Y-1.0       ( Increment Y by -1.0" to prepare for the next pass )
M99
( End of subroutine )

